/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sharian;

import analizadorLexico.Tokens;
import analizadorLexico.Lexer;
import analizadorSintactico.Parser;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;

/**
 *
 * @author CARLO
 */
public class Menu extends javax.swing.JFrame {

    private int contador = 1;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        jtaConsola = new javax.swing.JTextArea();
        jtaConsola.setEditable(false);
        jtaConsola.setBackground(new java.awt.Color(40, 42, 54));
        jtaConsola.setForeground(new java.awt.Color(0, 255, 0));
        jtaConsola.setFont(new java.awt.Font("Monospaced", 0, 14));
        jtaConsola.setRows(5);

        jScrollPaneConsola = new javax.swing.JScrollPane(jtaConsola);
        jScrollPaneConsola.setBorder(new javax.swing.border.TitledBorder("Consola de Salida"));
        initComponents();
    }
    
    private void analizarCodigo() {
    jtaConsola.setText("");
    JTextArea tabActual = tabActual();
    String codigo = tabActual.getText();
    Lexer scanner = new Lexer(new java.io.StringReader(codigo));
    List<TokenData> listaTokens = new ArrayList<>();
    try {
        while (true) {
            Tokens token = scanner.yylex();
            if (token == null) {
                break;
            }
            if (token == Tokens.ERROR) {
                jtaConsola.setText("ERROR: Simbolo desconocido: '" + scanner.lexeme + "'");
                return; // Cortamos la ejecución aquí
            }
            listaTokens.add(new TokenData(token, scanner.lexeme));
        }
        //analisis sintactico
        if(!listaTokens.isEmpty()){
            Parser parseador = new Parser(listaTokens);
            jtaConsola.setText(parseador.analizarSintaxis());
        }
        else{
            jtaConsola.setText("vacio");
        }
    } catch (java.io.IOException ex) {
        jtaConsola.append("Error fatal: " + ex.getMessage() + "\n");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaCode = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnCompilar = new javax.swing.JButton();
        jScrollPaneConsola = new javax.swing.JScrollPane();
        jtaConsola = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SaveFile = new javax.swing.JMenuItem();
        LoadFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(40, 42, 54));

        jPanel1.setBackground(new java.awt.Color(53, 55, 70));
        jPanel1.setForeground(new java.awt.Color(53, 55, 70));

        TabbedPane.setForeground(new java.awt.Color(9, 0, 58));

        jScrollPane2.setForeground(new java.awt.Color(62, 66, 68));
        jScrollPane2.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPane2.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jtaCode.setEditable(false);
        jtaCode.setBackground(new java.awt.Color(40, 42, 54));
        jtaCode.setColumns(20);
        jtaCode.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jtaCode.setForeground(new java.awt.Color(229, 229, 229));
        jtaCode.setRows(5);
        jtaCode.setText("Bienvenid@ a Sharian!!   Agrega una pestaña para comenzar :)");
        jtaCode.setToolTipText("");
        jtaCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jtaCode.setCaretColor(new java.awt.Color(255, 255, 255));
        jtaCode.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtaCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaCodeKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jtaCode);

        TabbedPane.addTab("tab1", jScrollPane2);

        btnAgregar.setBackground(new java.awt.Color(66, 68, 86));
        btnAgregar.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setFocusPainted(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setIconTextGap(3);
        btnAgregar.setMargin(null);
        btnAgregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(66, 68, 86));
        btnGuardar.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disquete.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setIconTextGap(3);
        btnGuardar.setMargin(null);
        btnGuardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCargar.setBackground(new java.awt.Color(66, 68, 86));
        btnCargar.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnCargar.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/carpeta.png"))); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.setBorder(null);
        btnCargar.setBorderPainted(false);
        btnCargar.setFocusPainted(false);
        btnCargar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCargar.setIconTextGap(3);
        btnCargar.setMargin(null);
        btnCargar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCargar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCargar.addActionListener(this::btnCargarActionPerformed);

        btnCompilar.setBackground(new java.awt.Color(66, 68, 86));
        btnCompilar.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnCompilar.setForeground(new java.awt.Color(255, 255, 255));
        btnCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/compilador.png"))); // NOI18N
        btnCompilar.setText("Compilar");
        btnCompilar.setBorder(null);
        btnCompilar.setBorderPainted(false);
        btnCompilar.setFocusPainted(false);
        btnCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompilar.setIconTextGap(3);
        btnCompilar.setMargin(null);
        btnCompilar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompilar.addActionListener(this::btnCompilarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(TabbedPane)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        jtaConsola.setColumns(20);
        jtaConsola.setRows(5);
        jScrollPaneConsola.setViewportView(jtaConsola);

        jMenuBar1.setBackground(new java.awt.Color(26, 27, 36));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 30));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("File");

        SaveFile.setText("Save");
        SaveFile.addActionListener(this::SaveFileActionPerformed);
        jMenu1.add(SaveFile);

        LoadFile.setText("Load");
        LoadFile.addActionListener(this::LoadFileActionPerformed);
        jMenu1.add(LoadFile);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneConsola))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
        // TODO add your handling code here:
        JTextArea tabActual = tabActual();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Script de Sharian");
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath();

            if (!ruta.endsWith(".shr")) {
                ruta = ruta + ".shr";
            }

            try (FileWriter writer = new FileWriter(ruta)) {
                writer.write(tabActual.getText());
                JOptionPane.showMessageDialog(this, "Archivo guardado en: " + ruta);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_SaveFileActionPerformed

    private void LoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadFileActionPerformed
        JFileChooser f = new JFileChooser();

        f.setFileSelectionMode(JFileChooser.FILES_ONLY);

        f.setAcceptAllFileFilterUsed(false);

        f.setFileFilter(new javax.swing.filechooser.FileFilter() {

            @Override
            public boolean accept(File file) {

                if (file.isDirectory()) {
                    return true;
                }

                return file.getName().toLowerCase().endsWith(".shr");
            }

            @Override
            public String getDescription() {
                return "Archivo .shr";
            }
        });

        int returnVal = f.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File archivo = f.getSelectedFile();

            try {

                String contenido = Files.readString(archivo.toPath());

                JTextArea area = new JTextArea();

                area.setBackground(new Color(40, 42, 54));
                area.setForeground(new Color(229,229,229));
                area.setCaretColor(Color.WHITE);
                area.setFont(new Font("SimSun", Font.PLAIN, 18));

                area.setText(contenido);

                JScrollPane scroll = new JScrollPane(area);

                scroll.setBorder(null);

                TabbedPane.addTab(
                        archivo.getName(),
                        scroll
                );

                TabbedPane.setSelectedComponent(scroll);

            } catch (IOException ex) {

                JOptionPane.showMessageDialog(
                        this,
                        "Error al leer archivo",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_LoadFileActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        JTextArea area = new JTextArea();

        area.setBackground(new Color(40, 42, 54));
        area.setForeground(new Color(229,229,229));
        area.setCaretColor(Color.WHITE);
        area.setFont(new Font("SimSun", Font.PLAIN, 18));

        JScrollPane scroll = new JScrollPane(area);

        TabbedPane.addTab(
                "Archivo" + contador + ".shr",
                scroll
        );

        contador++;
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        JTextArea tabActual = tabActual();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Script de Sharian");
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath();

            if (!ruta.endsWith(".shr")) {
                ruta = ruta + ".shr";
            }

            try (FileWriter writer = new FileWriter(ruta)) {
                writer.write(tabActual.getText());
                JOptionPane.showMessageDialog(this, "Archivo guardado en: " + ruta);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        JFileChooser f = new JFileChooser();

        f.setFileSelectionMode(JFileChooser.FILES_ONLY);

        f.setAcceptAllFileFilterUsed(false);

        f.setFileFilter(new javax.swing.filechooser.FileFilter() {

            @Override
            public boolean accept(File file) {

                if (file.isDirectory()) {
                    return true;
                }

                return file.getName().toLowerCase().endsWith(".shr");
            }

            @Override
            public String getDescription() {
                return "Archivo .shr";
            }
        });

        int returnVal = f.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File archivo = f.getSelectedFile();

            try {

                String contenido = Files.readString(archivo.toPath());

                JTextArea area = new JTextArea();

                area.setBackground(new Color(40, 42, 54));
                area.setForeground(new Color(229,229,229));
                area.setCaretColor(Color.WHITE);
                area.setFont(new Font("SimSun", Font.PLAIN, 18));

                area.setText(contenido);

                JScrollPane scroll = new JScrollPane(area);

                scroll.setBorder(null);

                TabbedPane.addTab(
                        archivo.getName(),
                        scroll
                );

                TabbedPane.setSelectedComponent(scroll);

            } catch (IOException ex) {

                JOptionPane.showMessageDialog(
                        this,
                        "Error al leer archivo",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        analizarCodigo();
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void jtaCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaCodeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtaCodeKeyTyped

    private JTextArea tabActual() {
        JScrollPane scroll = (JScrollPane) TabbedPane.getSelectedComponent();
        JViewport viewport = scroll.getViewport();
        return (JTextArea) viewport.getView();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LoadFile;
    private javax.swing.JMenuItem SaveFile;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneConsola;
    private javax.swing.JTextArea jtaCode;
    private javax.swing.JTextArea jtaConsola;
    // End of variables declaration//GEN-END:variables
}
